server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: bank_user
    password: bank_password

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  jwt:
    secret: "dev-jwt-secret"
    expiration: 86400000

springdoc:
  swagger-ui:
    enabled: true
